[package]
name = "yasbit"
version = "0.1.0"
authors = ["vruello <hello@vruello.fr>"]
edition = "2018"

[dependencies]
openssl = ""
hex = ""
rand = ""
dns-lookup = ""
log = ""
simple_logger = ""
rocksdb = ""
